# Generated by Django 4.2.9 on 2024-04-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_page_create_date_page_update_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="number",
            field=models.IntegerField(default=8, verbose_name="Magic Number"),
        ),
    ]
