# Generated by Django 4.2.9 on 2024-04-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_page_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="number",
            field=models.IntegerField(default=9, verbose_name="Magic Number"),
        ),
    ]
