# Generated by Django 4.2.9 on 2024-04-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_page_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="pic",
            field=models.ImageField(
                blank=True, default="placeholder.png", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="number",
            field=models.IntegerField(default=8, verbose_name="Magic Number"),
        ),
    ]
