# Generated by Django 4.2.9 on 2024-04-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_page_pic_alter_page_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="number",
            field=models.IntegerField(default=5, verbose_name="Magic Number"),
        ),
    ]
