# Generated by Django 4.2.9 on 2024-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_page_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="number",
            field=models.IntegerField(default=8, verbose_name="Magic Number"),
        ),
    ]
